version: "3.8"
networks:
  WPBoard:
services:
  nginx:
    image: nginx:stable-alpine
    container_name: WPBoard_Nginx
    ports:
      - "7668:80"
    volumes:
      - ./public_html:/var/www/html:ro
      - ./wheeparam:/var/www/wheeparam
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - WPBoard
  php:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: WPBoard_php
    volumes:
      - ./public_html:/var/www/html
      - ./wheeparam:/var/www/wheeparam
    ports:
      - "9000:9000"
    networks:
      - WPBoard
    environment:
      CI_ENV: development